= iui-seed-ratpack

== iUI Seed Project using Ratpack project template

This is a prototype "seed" project that uses http://www.iui-js.org[iUI] on the client and http://www.ratpack-framework.org[Ratpack] on the server.

Created using the https://github.com/pledbrook/lazybones/tree/master/src/templates/ratpack[Ratpack template] from https://github.com/pledbrook/lazybones[Lazybones]

Very similar structure to the https://github.com/ratpack/example-ratpack-gradle-groovy-app[Example Ratpack Gradle/Groovy App] which has a https://github.com/ratpack/example-ratpack-gradle-groovy-app#readme[better README].

== Directory Structure

Unlike a typical Ratpack Gradle/Groovy App, the +ratpack+ directory is not in +src/ratpack+.  Instead the contents of that directory are in the project root directory.

  * +public+ - directory contains static HTML and resources
  * +templates+ - directory contains Groovy templates (HTML with some Groovy variables)
  * +ratpack.groovy+ - Ratpack routes, code to set template variables, etc.
  
== Running

 ./gradlew run
    
== Building

To make a full copy of the app in the +build/install/iui-seed-ratpack+ directory:

 ./gradlew installApp
    
To run that app:

 cd build/install/iui-seed-ratpack
 build/install/iui-seed-ratpack
    
To make a zip in +build/distributions/iui-seed-ratpack.zip+:

 ./gradlew distZip

